services:

  identix:
    container_name: overoom.identix
    build:
      context: "./src"
      dockerfile: "Identix/Dockerfile"
      target: "base"
    environment:
      ASPNETCORE_ENVIRONMENT: "DevContainer"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net10.0/Identix.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "identix"
    entrypoint:
      - "dotnet"
      - "/app/bin/Debug/net10.0/Identix.dll"
    ports:
      - "443:443"
    volumes:
      - "./development/configurations/identix/appsettings.DevContainer.json:/app-1/appsettings.DevContainer.json"
      - "./development/configurations/ssl:/https:ro"
      - "~/.nuget/packages:/home/app/.nuget/packages"
      - "./src/Identix:/app:rw"
      - "./src:/src:rw"
    working_dir: "/app"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
      rustfs:
        condition: service_healthy

  films:
    container_name: overoom.films
    build:
      context: "./src"
      dockerfile: "Films.Start/Dockerfile"
      target: "base"
    environment:
      ASPNETCORE_ENVIRONMENT: "DevContainer"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "films"
    entrypoint:
      - "dotnet"
      - "/app/bin/Debug/net10.0/Films.Start.dll"
    ports:
      - "7131:443"
    volumes:
      - "./development/configurations/films/appsettings.DevContainer.json:/app-1/appsettings.DevContainer.json"
      - "./development/configurations/ssl:/https:ro"
      - "~/.nuget/packages:/home/app/.nuget/packages"
      - "./src/Films.Start:/app:rw"
      - "./src:/src:rw"
    working_dir: "/app"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
      rustfs:
        condition: service_healthy

  rooms:
    container_name: overoom.rooms
    build:
      context: "./src"
      dockerfile: "Rooms.Start/Dockerfile"
      target: "base"
    environment:
      ASPNETCORE_ENVIRONMENT: "DevContainer"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "rooms"
    entrypoint:
      - "dotnet"
      - "/app/bin/Debug/net10.0/Rooms.Start.dll"
    ports:
      - "7291:443"
    volumes:
      - "./development/configurations/rooms/appsettings.DevContainer.json:/app-1/appsettings.DevContainer.json"
      - "./development/configurations/ssl:/https:ro"
      - "~/.nuget/packages:/home/app/.nuget/packages"
      - "./src/Rooms.Start:/app:rw"
      - "./src:/src:rw"
    working_dir: "/app"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:8.3.11
    container_name: overoom.mongo
    ports:
      - '27017:27017'
    volumes:
      - "./development/configurations/mongo/:/mongo/config"
      - './development/containers/mongo/:/data/db'
    command: [ "--replSet", "rs0", "--bind_ip_all" ]
    healthcheck:
      test: [ "CMD-SHELL", "/mongo/config/healthcheck.sh" ]
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: overoom.mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/admin?retryWrites=true&loadBalanced=false&connectTimeoutMS=10000
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      mongo:
        condition: service_healthy

  rabbitmq:
    build: "./rabbitmq"
    image: "overoom.rabbitmq:4.2.9"
    container_name: overoom.rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rustfs:
    image: rustfs/rustfs:1.0.0
    container_name: overoom.rustfs
    environment:
      - RUSTFS_ACCESS_KEY=admin
      - RUSTFS_SECRET_KEY=admin
      - RUSTFS_CONSOLE_ENABLE=true
    volumes:
      - './development/containers/rustfs/:/data/'
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  prometheus:
    image: prom/prometheus:v3.15.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'
    volumes:
      - "./development/configurations/prometheus/:/etc/prometheus"
    ports:
      - "9090:9090"
    healthcheck:
      test: [ "CMD-SHELL", "/etc/prometheus/healthcheck.sh" ]
      interval: 5s
      timeout: 5s
      retries: 5
