services:
  authservice.postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
    ports:
      - 5432:5432
  films.postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
    ports:
      - 5433:5432
