services:
  rabbitmq:
    image: rabbitmq:3.12.10-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - 15672:15672
      - 5672:5672

  auth.postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
    ports:
      - 5432:5432
    volumes:
      - ./containers/auth:/var/lib/postgresql/data

  films.postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
    ports:
      - 5433:5432
    volumes:
      - ./containers/films:/var/lib/postgresql/data

  rooms-1.postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
    ports:
      - 5434:5432
    volumes:
      - ./containers/rooms-1:/var/lib/postgresql/data