//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJMS.AuthService.Mail.Resources.AppEmailService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PJMS.AuthService.Mail.Resources.AppEmailService.EmailService", typeof(EmailService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code expires 1 minute after generation..
        /// </summary>
        internal static string CodeExpires {
            get {
                return ResourceManager.GetString("CodeExpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your email.
        /// </summary>
        internal static string ConfirmMailChangeEmailButtonName {
            get {
                return ResourceManager.GetString("ConfirmMailChangeEmailButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received this email because you requested a change of email address..
        /// </summary>
        internal static string ConfirmMailChangeEmailExplanation {
            get {
                return ResourceManager.GetString("ConfirmMailChangeEmailExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the mail.
        /// </summary>
        internal static string ConfirmMailChangeEmailSubject {
            get {
                return ResourceManager.GetString("ConfirmMailChangeEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the change of your email address to a new one by clicking on the button below..
        /// </summary>
        internal static string ConfirmMailChangeEmailText {
            get {
                return ResourceManager.GetString("ConfirmMailChangeEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover password.
        /// </summary>
        internal static string ConfirmRecoverPasswordEmailButtonName {
            get {
                return ResourceManager.GetString("ConfirmRecoverPasswordEmailButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received this email because you requested to restore your password..
        /// </summary>
        internal static string ConfirmRecoverPasswordEmailExplanation {
            get {
                return ResourceManager.GetString("ConfirmRecoverPasswordEmailExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        internal static string ConfirmRecoverPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ConfirmRecoverPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the reset of the old password by clicking on the button below. This step will delete your old password and allow you to set a new one..
        /// </summary>
        internal static string ConfirmRecoverPasswordEmailText {
            get {
                return ResourceManager.GetString("ConfirmRecoverPasswordEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm registration.
        /// </summary>
        internal static string ConfirmRegistrationEmailButtonName {
            get {
                return ResourceManager.GetString("ConfirmRegistrationEmailButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received this email because you have recently registered an account..
        /// </summary>
        internal static string ConfirmRegistrationEmailExplanation {
            get {
                return ResourceManager.GetString("ConfirmRegistrationEmailExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account activation.
        /// </summary>
        internal static string ConfirmRegistrationEmailSubject {
            get {
                return ResourceManager.GetString("ConfirmRegistrationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your email address by clicking on the button below. This step increases the security of your business by confirming that you are the owner of this email address..
        /// </summary>
        internal static string ConfirmRegistrationEmailText {
            get {
                return ResourceManager.GetString("ConfirmRegistrationEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link expires 24 hours after receiving the email..
        /// </summary>
        internal static string LinkExpires {
            get {
                return ResourceManager.GetString("LinkExpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You received this email because you requested a two-factor authentication code..
        /// </summary>
        internal static string TwoFactorCodeEmailExplanation {
            get {
                return ResourceManager.GetString("TwoFactorCodeEmailExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting a two-factor authentication code.
        /// </summary>
        internal static string TwoFactorCodeEmailSubject {
            get {
                return ResourceManager.GetString("TwoFactorCodeEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code below into the application to complete two-factor authentication..
        /// </summary>
        internal static string TwoFactorCodeEmailText {
            get {
                return ResourceManager.GetString("TwoFactorCodeEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
