//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJMS.AuthService.Resources.Views.TwoFactor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Setup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PJMS.AuthService.Resources.Views.TwoFactor.Setup", typeof(Setup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or Google Authenticator for.
        /// </summary>
        internal static string DownloadGoogle {
            get {
                return ResourceManager.GetString("DownloadGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Download a two-factor authentication application such as Microsoft Authenticator for.
        /// </summary>
        internal static string DownloadMicrosoft {
            get {
                return ResourceManager.GetString("DownloadMicrosoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the QR code does not work, try to increase the brightness of the screen..
        /// </summary>
        internal static string QrCodeInvalid {
            get {
                return ResourceManager.GetString("QrCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to your application for two-factor authentication..
        /// </summary>
        internal static string ScanQrOrEnterKeyEnd {
            get {
                return ResourceManager.GetString("ScanQrOrEnterKeyEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Scan the QR code or enter the following key.
        /// </summary>
        internal static string ScanQrOrEnterKeyStart {
            get {
                return ResourceManager.GetString("ScanQrOrEnterKeyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on.
        /// </summary>
        internal static string SetUp {
            get {
                return ResourceManager.GetString("SetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        internal static string SetupTwoFactorTitle {
            get {
                return ResourceManager.GetString("SetupTwoFactorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case and spaces do not matter..
        /// </summary>
        internal static string SpacesNotMatter {
            get {
                return ResourceManager.GetString("SpacesNotMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. After you have scanned the QR code or entered the above key, your two-factor authentication application will provide you with a unique code. Enter this code in the confirmation field below..
        /// </summary>
        internal static string UniqueCode {
            get {
                return ResourceManager.GetString("UniqueCode", resourceCulture);
            }
        }
    }
}
