<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Uploader.Application.Abstractions\Uploader.Application.Abstractions.csproj"/>
        <ProjectReference Include="..\Common.IntegrationEvents\Common.IntegrationEvents.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.5.10"/>
        <PackageReference Include="MassTransit.MongoDb" Version="8.5.10"/>
    </ItemGroup>

</Project>
