//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identix.Infrastructure.Web.Resources.Home.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomeController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Identix.Infrastructure.Web.Resources.Home.Controllers.HomeController", typeof(HomeController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the request..
        /// </summary>
        internal static string DefaultMessage {
            get {
                return ResourceManager.GetString("DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mail is already in use.
        /// </summary>
        internal static string EmailAlreadyTakenException {
            get {
                return ResourceManager.GetString("EmailAlreadyTakenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mail format is not correct.
        /// </summary>
        internal static string EmailFormatException {
            get {
                return ResourceManager.GetString("EmailFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message could not be sent to your email..
        /// </summary>
        internal static string EmailSendException {
            get {
                return ResourceManager.GetString("EmailSendException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error via an external service.
        /// </summary>
        internal static string ExternalAuthenticationFailureException {
            get {
                return ResourceManager.GetString("ExternalAuthenticationFailureException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link has expired.
        /// </summary>
        internal static string InvalidCodeException {
            get {
                return ResourceManager.GetString("InvalidCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is already linked to another user.
        /// </summary>
        internal static string LoginAlreadyAssociatedException {
            get {
                return ResourceManager.GetString("LoginAlreadyAssociatedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login not found.
        /// </summary>
        internal static string LoginNotFoundException {
            get {
                return ResourceManager.GetString("LoginNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested page was not found.
        /// </summary>
        internal static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action is not available out of context. Go back to the main app and try again..
        /// </summary>
        internal static string OpenIdContextException {
            get {
                return ResourceManager.GetString("OpenIdContextException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query string parameter is missing.
        /// </summary>
        internal static string QueryParameterMissingException {
            get {
                return ResourceManager.GetString("QueryParameterMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication is already enabled.
        /// </summary>
        internal static string TwoFactorAlreadyEnabledException {
            get {
                return ResourceManager.GetString("TwoFactorAlreadyEnabledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been blocked due to a large number of failed login attempts. Try logging in later.
        /// </summary>
        internal static string UserLockoutException {
            get {
                return ResourceManager.GetString("UserLockoutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username length.
        /// </summary>
        internal static string UserNameLengthException {
            get {
                return ResourceManager.GetString("UserNameLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was not found.
        /// </summary>
        internal static string UserNotFoundException {
            get {
                return ResourceManager.GetString("UserNotFoundException", resourceCulture);
            }
        }
    }
}
