//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identix.Infrastructure.Web.Resources.Settings.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Identix.Infrastructure.Web.Resources.Settings.Controllers.SettingsController", typeof(SettingsController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile photo has been changed.
        /// </summary>
        internal static string AvatarChanged {
            get {
                return ResourceManager.GetString("AvatarChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mail is already in use.
        /// </summary>
        internal static string EmailAlreadyTaken {
            get {
                return ResourceManager.GetString("EmailAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mail has been changed.
        /// </summary>
        internal static string EmailChanged {
            get {
                return ResourceManager.GetString("EmailChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has been sent to your old email address.
        /// </summary>
        internal static string EmailChangeRequested {
            get {
                return ResourceManager.GetString("EmailChangeRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mail format is not correct.
        /// </summary>
        internal static string EmailFormatInvalid {
            get {
                return ResourceManager.GetString("EmailFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To perform this action, confirm your email.
        /// </summary>
        internal static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password cannot match the old one.
        /// </summary>
        internal static string OldPasswordMatchNew {
            get {
                return ResourceManager.GetString("OldPasswordMatchNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the old password to change it.
        /// </summary>
        internal static string OldPasswordNeeded {
            get {
                return ResourceManager.GetString("OldPasswordNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been successfully changed.
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password length.
        /// </summary>
        internal static string PasswordLengthInvalid {
            get {
                return ResourceManager.GetString("PasswordLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password is incorrect.
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain numbers.
        /// </summary>
        internal static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain lowercase letters.
        /// </summary>
        internal static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain special characters.
        /// </summary>
        internal static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain uppercase letters.
        /// </summary>
        internal static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider {0} is linked.
        /// </summary>
        internal static string ProviderLinked {
            get {
                return ResourceManager.GetString("ProviderLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider {0} is unlinked.
        /// </summary>
        internal static string ProviderUnlinked {
            get {
                return ResourceManager.GetString("ProviderUnlinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other sessions have been completed successfully.
        /// </summary>
        internal static string SessionsClosed {
            get {
                return ResourceManager.GetString("SessionsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s name has been changed.
        /// </summary>
        internal static string UserNameChanged {
            get {
                return ResourceManager.GetString("UserNameChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username length.
        /// </summary>
        internal static string UserNameLengthInvalid {
            get {
                return ResourceManager.GetString("UserNameLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size cannot exceed 15 MB.
        /// </summary>
        internal static string WrongFileSize {
            get {
                return ResourceManager.GetString("WrongFileSize", resourceCulture);
            }
        }
    }
}
